### ISSUE TITLE
Isuse with npm start

### ISSUE THREAD

**Issue by Neetesh1** [onehungrymind/ng2-rest-app#3]
Hi I an windows user and getting below error when i run the npm start command.

ERROR in C:/Users/neetesh.vishwakarma/angular2/new/ng2-rest-app/node_modules s/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'O vable<T>'.

**Comment by jdgarvey** [comment]
Hi @Neetesh1 
We tried running the app on a Windows machine and it seemed to work ok. 

The first course of action would be for you to delete the `node_modules` folder in the root of the project, then run `npm cache clean` and `npm i` to get a fresh install of all the dependencies.

If the error persists, we need some information to debug:

* A full stack trace of the error in your terminal
* Output from running `npm ls --depth=0`
* Node.js and NPM versions (`node -v` and `npm -v`, respectively)
* What OS you are running

Thanks!

**Comment by Neetesh1** [comment]
Thanks @jdgarvey , **npm cache clean** works for me
